INSERT INTO Products (ProductCode, Name, Description, Price) VALUES
(NEWID(), 'Tablet A1', 'Yüksek performanslı tablet', 2999.99),
(NEWID(), 'Telefon X', 'En yeni akıllı telefon modeli', 8999.99),
(NEWID(), 'Dizüstü Bilgisayar Pro 15', 'Profesyonel dizüstü bilgisayar', 14999.99),
(NEWID(), 'Kulaklık Z', 'Gürültü önleyici kulaklık', 1999.99),
(NEWID(), 'Akıllı Saat Y', 'Fitness takip özellikli akıllı saat', 1499.99),
(NEWID(), 'Oyun Konsolu B', 'Yeni nesil oyun konsolu', 4999.99),
(NEWID(), 'Kamera Q', 'Yüksek çözünürlüklü dijital kamera', 7999.99),
(NEWID(), 'Bluetooth Hoparlör S', 'Taşınabilir Bluetooth hoparlör', 999.99),
(NEWID(), '4K TV 55"', 'Ultra HD Akıllı TV', 9999.99),
(NEWID(), 'Yönlendirici R1', 'Yüksek hızlı Wi-Fi yönlendirici', 1299.99),
(NEWID(), 'Tablet B2', 'Orta seviye tablet', 1999.99),
(NEWID(), 'Telefon Y', 'Gelişmiş özelliklere sahip telefon', 6999.99),
(NEWID(), 'Dizüstü Bilgisayar Air 13', 'Hafif ve taşınabilir dizüstü bilgisayar', 11999.99),
(NEWID(), 'Kulaklık X', 'Kablosuz kulaklık', 999.99),
(NEWID(), 'Akıllı Saat Z', 'Sağlık izleme özellikli akıllı saat', 1999.99),
(NEWID(), 'Oyun Konsolu C', 'Klasik oyun konsolu', 2999.99),
(NEWID(), 'Kamera R', 'Profesyonel fotoğraf makinesi', 9999.99),
(NEWID(), 'Bluetooth Hoparlör T', 'Yüksek ses kalitesine sahip hoparlör', 1499.99),
(NEWID(), 'LED TV 65"', 'Büyük ekran LED TV', 15999.99),
(NEWID(), 'Yönlendirici R2', 'Gelişmiş özelliklere sahip yönlendirici', 1599.99),
(NEWID(), 'Tablet C3', 'Giriş seviyesi tablet', 999.99),
(NEWID(), 'Telefon Z', 'Ekonomik akıllı telefon', 3999.99),
(NEWID(), 'Dizüstü Bilgisayar Ultra 17', 'Yüksek performanslı büyük ekran dizüstü bilgisayar', 19999.99),
(NEWID(), 'Kulaklık Y', 'Spor yaparken kullanılabilecek kulaklık', 599.99),
(NEWID(), 'Akıllı Saat X', 'Gelişmiş akıllı saat', 2499.99),
(NEWID(), 'Oyun Konsolu D', 'Retro oyun konsolu', 1999.99),
(NEWID(), 'Kamera S', 'Kompakt dijital kamera', 2999.99),
(NEWID(), 'Bluetooth Hoparlör U', 'Su geçirmez Bluetooth hoparlör', 1999.99),
(NEWID(), 'OLED TV 55"', 'Yüksek çözünürlüklü OLED TV', 18999.99),
(NEWID(), 'Yönlendirici R3', 'Mesh Wi-Fi yönlendirici', 1999.99),
(NEWID(), 'Tablet D4', 'Çocuklar için tablet', 699.99),
(NEWID(), 'Telefon A', 'Eski model telefon', 1999.99),
(NEWID(), 'Dizüstü Bilgisayar Flex 14', 'Dokunmatik ekranlı dizüstü bilgisayar', 12999.99),
(NEWID(), 'Kulaklık W', 'Oyuncular için kulaklık', 2999.99),
(NEWID(), 'Akıllı Saat W', 'Çocuklar için akıllı saat', 999.99),
(NEWID(), 'Oyun Konsolu E', 'Hareket algılayıcı özellikli oyun konsolu', 3999.99),
(NEWID(), 'Kamera T', 'Vlog kamerası', 4999.99),
(NEWID(), 'Bluetooth Hoparlör V', '360 derece ses hoparlörü', 2499.99),
(NEWID(), 'LED TV 75"', 'Dev ekran LED TV', 20999.99),
(NEWID(), 'Yönlendirici R4', 'Güvenlik özellikli yönlendirici', 999.99),
(NEWID(), 'Tablet E5', 'Windows işletim sistemli tablet', 3499.99),
(NEWID(), 'Telefon B', 'Düşük bütçeli telefon', 999.99),
(NEWID(), 'Dizüstü Bilgisayar Nano 13', 'Ultra hafif dizüstü bilgisayar', 10999.99),
(NEWID(), 'Kulaklık V', 'Kablolu kulaklık', 199.99),
(NEWID(), 'Akıllı Saat V', 'Yetişkinler için akıllı saat', 1799.99),
(NEWID(), 'Oyun Konsolu F', 'VR destekli oyun konsolu', 5999.99),
(NEWID(), 'Kamera U', 'Hızlı çekim özellikli kamera', 3999.99),
(NEWID(), 'Bluetooth Hoparlör W', 'Büyük boy Bluetooth hoparlör', 2999.99),
(NEWID(), 'OLED TV 65"', 'Büyük ekran OLED TV', 23999.99),
(NEWID(), 'Yönlendirici R5', 'Çok antenli yönlendirici', 2499.99),
(NEWID(), 'Tablet F6', 'Yüksek çözünürlüklü ekranlı tablet', 2499.99),
(NEWID(), 'Telefon C', 'Gelişmiş özellikli telefon', 4999.99),
(NEWID(), 'Dizüstü Bilgisayar Eco 15', 'Enerji tasarruflu dizüstü bilgisayar', 8999.99),
(NEWID(), 'Kulaklık U', 'Kablosuz kulaklık', 799.99),
(NEWID(), 'Akıllı Saat U', 'Sporcular için akıllı saat', 2299.99),
(NEWID(), 'Oyun Konsolu G', 'Taşınabilir oyun konsolu', 2999.99),
(NEWID(), 'Kamera V', 'Profesyonel video kamera', 8999.99),
(NEWID(), 'Bluetooth Hoparlör X', 'Yüksek ses çıkışlı hoparlör', 3499.99),
(NEWID(), 'LED TV 85"', 'Dev ekran LED TV', 25999.99),
(NEWID(), 'Yönlendirici R6', 'Uzun menzilli yönlendirici', 1999.99),
(NEWID(), 'Tablet G7', 'Hibrit tablet', 3999.99),
(NEWID(), 'Telefon D', 'Yeni nesil akıllı telefon', 7999.99),
(NEWID(), 'Dizüstü Bilgisayar Prime 17', 'Yüksek performanslı büyük ekran dizüstü bilgisayar', 24999.99),
(NEWID(), 'Kulaklık T', 'Yüksek kaliteli kulaklık', 2499.99),
(NEWID(), 'Akıllı Saat T', 'Sağlık izleme özellikli akıllı saat', 2699.99),
(NEWID(), 'Oyun Konsolu H', '4K oyun konsolu', 4499.99),
(NEWID(), 'Kamera W', 'Güvenlik kamerası', 1999.99),
(NEWID(), 'Bluetooth Hoparlör Y', 'Çift hoparlör seti', 3999.99),
(NEWID(), 'OLED TV 75"', 'Ultra HD OLED TV', 28999.99),
(NEWID(), 'Yönlendirici R7', 'Kurumsal yönlendirici', 4999.99),
(NEWID(), 'Tablet H8', 'Grafik tablet', 4599.99),
(NEWID(), 'Telefon E', 'Yeni özellikli telefon', 5999.99),
(NEWID(), 'Dizüstü Bilgisayar Pro 13', 'Profesyonel dizüstü bilgisayar', 16999.99),
(NEWID(), 'Kulaklık S', 'Kompakt kulaklık', 499.99),
(NEWID(), 'Akıllı Saat S', 'Sağlık izleme özellikli akıllı saat', 2199.99),
(NEWID(), 'Oyun Konsolu I', 'Yeni nesil oyun konsolu', 5499.99),
(NEWID(), 'Kamera X', 'Yüksek çözünürlüklü kamera', 6999.99),
(NEWID(), 'Bluetooth Hoparlör Z', 'Çok yönlü Bluetooth hoparlör', 4499.99),
(NEWID(), 'LED TV 95"', 'Dev ekran LED TV', 29999.99),
(NEWID(), 'Yönlendirici R8', 'Gelişmiş özelliklere sahip yönlendirici', 3499.99),
(NEWID(), 'Tablet I9', 'Yeni nesil tablet', 4999.99),
(NEWID(), 'Telefon F', 'Yüksek performanslı telefon', 6999.99),
(NEWID(), 'Dizüstü Bilgisayar Flex 16', 'Esnek ekranlı dizüstü bilgisayar', 17999.99),
(NEWID(), 'Kulaklık R', 'Oyuncular için kablosuz kulaklık', 3499.99),
(NEWID(), 'Akıllı Saat R', 'Sporcular için gelişmiş akıllı saat', 2799.99),
(NEWID(), 'Oyun Konsolu J', 'Retro oyun konsolu', 2499.99),
(NEWID(), 'Kamera Y', 'Yüksek hızlı çekim özellikli kamera', 7999.99),
(NEWID(), 'Bluetooth Hoparlör A', 'Taşınabilir Bluetooth hoparlör', 2999.99),
(NEWID(), 'OLED TV 85"', 'Büyük ekran OLED TV', 31999.99),
(NEWID(), 'Yönlendirici R9', 'Çok antenli uzun menzilli yönlendirici', 3999.99);